M48
; DRILL file {KiCad 9.0.0} date 2025-10-31T12:43:10+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-31T12:43:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X16.25Y-10.5
X16.25Y-67.4
X41.7Y-4.97
X89.55Y-10.5
X89.55Y-67.4
X94.0Y-34.0
X94.0Y-73.4
M30
